version: '3.4'

services:
  crudmicroservice:
    image: crudmicroservice:dev
    container_name: Crud_microservice
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Crud microservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_crudmicroservice$
    volumes:
      - C:\Users\Pavilion\source\repos\Crud microservice\Crud microservice:/app
      - C:\Users\Pavilion\source\repos\Crud microservice:/src
      - C:\Users\Pavilion\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_crudmicroservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_crudmicroservice$ \"/app/bin/Debug/net5.0/Crud microservice.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true